services:
  mysql:
    image: mysql:8.0
    container_name: anime_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: anime_db
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: anime_springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/anime_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  mysql_data:
